"""add visit count

Revision ID: 82e7405018f7
Revises: be90cdf0b0ac
Create Date: 2026-09-01 19:36:04.614206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e7405018f7'
down_revision: Union[str, Sequence[str], None] = 'be90cdf0b0ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('visit_count', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'visit_count')
    # ### end Alembic commands ###
