"""short_code_unique

Revision ID: be90cdf0b0ac
Revises: 5e54e420a7ad
Create Date: 2026-08-27 19:51:56.593978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be90cdf0b0ac'
down_revision: Union[str, Sequence[str], None] = '5e54e420a7ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_urls_short_code', 'urls', ['short_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_urls_short_code', 'urls', type_='unique')
    # ### end Alembic commands ###
